#### Problem Statement
Your client is a large MNC and they have 9 broad verticals across the organisation. One of the problem your client is facing is around identifying the right people for promotion (only for manager position and below) and prepare them in time. Currently the process, they are following is:

1. They first identify a set of employees based on recommendations/ past performance

2.Selected employees go through the separate training and evaluation program for each vertical. These programs are based on the required skill of each vertical

3.At the end of the program, based on various factors such as training performance, KPI completion (only employees with KPIs completed greater than 60% are considered) etc., employee gets promotion

For above mentioned process, the final promotions are only announced after the evaluation and this leads to delay in transition to their new roles. Hence, company needs your help in identifying the eligible candidates at a particular checkpoint so that they can expedite the entire promotion cycle.

In [ ]:
#imp recommendation ,past performance ,tranning performance ,kpi>60%, 

In [17]:
import pandas as pd
import numpy as np

In [3]:
path_sample=r"E:\APEXTECHNOMATICS\sample_submission_M0L0uXE.csv"
sample=pd.read_csv(path_sample,index_col=0).head()
sample

is_promoted
employee_id             
8724                   0
74430                  0
72255                  0
38562                  0
64486                  0

In [4]:
path_test=r"E:\APEXTECHNOMATICS\test_2umaH9m.csv"
test=pd.read_csv(path_test,index_col=0).head()
test

department     region   education gender  \
employee_id                                                    
8724                Technology  region_26  Bachelor's      m   
74430                       HR   region_4  Bachelor's      f   
72255        Sales & Marketing  region_13  Bachelor's      m   
38562              Procurement   region_2  Bachelor's      f   
64486                  Finance  region_29  Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
8724                   sourcing                1   24                   NaN   
74430                     other                1   31                   3.0   
72255                     other                1   31                   1.0   
38562                     other                3   31                   2.0   
64486                  sourcing                1   30                   4.0   

             length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
employee_id                                                                     
8724                         1              1            0                  77  
74430                        5              0            0                  51  
72255                        4              0            0                  47  
38562                        9              0            0                  65  
64486                        7              0            0                  61

In [5]:
path_train=r"E:\APEXTECHNOMATICS\train_LZdllcl.csv"
train=pd.read_csv(path_train,index_col=0).head()
train

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [6]:
train.describe()

no_of_trainings        age  previous_year_rating  length_of_service  \
count         5.000000   5.000000               5.00000           5.000000   
mean          1.200000  36.600000               3.40000           6.200000   
std           0.447214   5.683309               1.67332           3.193744   
min           1.000000  30.000000               1.00000           2.000000   
25%           1.000000  34.000000               3.00000           4.000000   
50%           1.000000  35.000000               3.00000           7.000000   
75%           1.000000  39.000000               5.00000           8.000000   
max           2.000000  45.000000               5.00000          10.000000   

       KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
count       5.000000          5.0            5.000000          5.0  
mean        0.200000          0.0           56.400000          0.0  
std         0.447214          0.0           10.310189          0.0  
min         0.000000          0.0           49.000000          0.0  
25%         0.000000          0.0           50.000000          0.0  
50%         0.000000          0.0           50.000000          0.0  
75%         0.000000          0.0           60.000000          0.0  
max         1.000000          0.0           73.000000          0.0

In [9]:
test.describe()

no_of_trainings       age  previous_year_rating  length_of_service  \
count         5.000000   5.00000              4.000000            5.00000   
mean          1.400000  29.40000              2.500000            5.20000   
std           0.894427   3.04959              1.290994            3.03315   
min           1.000000  24.00000              1.000000            1.00000   
25%           1.000000  30.00000              1.750000            4.00000   
50%           1.000000  31.00000              2.500000            5.00000   
75%           1.000000  31.00000              3.250000            7.00000   
max           3.000000  31.00000              4.000000            9.00000   

       KPIs_met >80%  awards_won?  avg_training_score  
count       5.000000          5.0            5.000000  
mean        0.200000          0.0           60.200000  
std         0.447214          0.0           11.882761  
min         0.000000          0.0           47.000000  
25%         0.000000          0.0           51.000000  
50%         0.000000          0.0           61.000000  
75%         0.000000          0.0           65.000000  
max         1.000000          0.0           77.000000

In [8]:
sample.describe()

is_promoted
count          5.0
mean           0.0
std            0.0
min            0.0
25%            0.0
50%            0.0
75%            0.0
max            0.0

In [ ]:
# drop department, region,gender,education,age,length_of_service as they are not in focus

#factors that matters
#1.They first identify a set of employees based on recommendations/ past performance
#2.Selected employees go through the separate training and evaluation program for each vertical. 
#3.At the end of the program, based on various factors such as training performance, KPI completion
#(only employees with KPIs completed greater than 60% are considered) etc., employee gets promotion

In [13]:
#onehot encoder

train_new=train.drop(columns=["department","region","gender","age"])

In [16]:
test_new=test.drop(columns=["department","region","gender","age"])

In [18]:
'''from sklearn.preprocessing import OneHotEncoder 
  
# creating one hot encoder object with categorical feature 0 
# indicating the first column 
onehotencoder = OneHotEncoder(categorical_features = [0]) '''


In [39]:
train_target=train_new["is_promoted"]
train_new=train_new.drop(columns="is_promoted")

In [40]:
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
train_new['education']= le.fit_transform(train_new['education']) 
train_new['recruitment_channel']= le.fit_transform(train_new['recruitment_channel'])

In [41]:
train_new

education  recruitment_channel  no_of_trainings  \
employee_id                                                    
65438                1                    1                1   
65141                0                    0                1   
7513                 0                    1                1   
2542                 0                    0                2   
48945                0                    0                1   

             previous_year_rating  length_of_service  KPIs_met >80%  \
employee_id                                                           
65438                         5.0                  8              1   
65141                         5.0                  4              0   
7513                          3.0                  7              0   
2542                          1.0                 10              0   
48945                         3.0                  2              0   

             awards_won?  avg_training_score  
employee_id                                   
65438                  0                  49  
65141                  0                  60  
7513                   0                  50  
2542                   0                  50  
48945                  0                  73

In [42]:

test_new['education']= le.fit_transform(test_new['education']) 
test_new['recruitment_channel']= le.fit_transform(test_new['recruitment_channel'])
test_new=test_new.fillna(0)
test_new

education  recruitment_channel  no_of_trainings  \
employee_id                                                    
8724                 0                    1                1   
74430                0                    0                1   
72255                0                    0                1   
38562                0                    0                3   
64486                0                    1                1   

             previous_year_rating  length_of_service  KPIs_met >80%  \
employee_id                                                           
8724                          0.0                  1              1   
74430                         3.0                  5              0   
72255                         1.0                  4              0   
38562                         2.0                  9              0   
64486                         4.0                  7              0   

             awards_won?  avg_training_score  
employee_id                                   
8724                   0                  77  
74430                  0                  51  
72255                  0                  47  
38562                  0                  65  
64486                  0                  61

In [43]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler().fit(train_new) 
train_new_X = scaler.transform(train_new) 
train_new_X

array([[ 2.        ,  1.22474487, -0.5       ,  1.06904497,  0.63012604,
         2.        ,  0.        , -0.8024539 ],
       [-0.5       , -0.81649658, -0.5       ,  1.06904497, -0.77015405,
        -0.5       ,  0.        ,  0.39038298],
       [-0.5       ,  1.22474487, -0.5       , -0.26726124,  0.28005602,
        -0.5       ,  0.        , -0.69401419],
       [-0.5       , -0.81649658,  2.        , -1.60356745,  1.33026608,
        -0.5       ,  0.        , -0.69401419],
       [-0.5       , -0.81649658, -0.5       , -0.26726124, -1.47029409,
        -0.5       ,  0.        ,  1.8000993 ]])

In [44]:
scaler_test = StandardScaler().fit(test_new) 
test_new_X = scaler_test.transform(test_new) 
test_new_X#test purpose

array([[ 0.        ,  1.22474487, -0.5       , -1.41421356, -1.54814054,
         2.        ,  0.        ,  1.58069085],
       [ 0.        , -0.81649658, -0.5       ,  0.70710678, -0.07372098,
        -0.5       ,  0.        , -0.86561642],
       [ 0.        , -0.81649658, -0.5       , -0.70710678, -0.44232587,
        -0.5       ,  0.        , -1.24197138],
       [ 0.        , -0.81649658,  2.        ,  0.        ,  1.40069858,
        -0.5       ,  0.        ,  0.45162596],
       [ 0.        ,  1.22474487, -0.5       ,  1.41421356,  0.6634888 ,
        -0.5       ,  0.        ,  0.07527099]])

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(train_new_X,train_target,test_size=0.2,random_state=0)#random state is 0 so we get the same results


In [46]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4, 8)
(4,)
(1, 8)
(1,)


In [49]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()



In [50]:
classifier.fit(X_train,y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

In [51]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion = 'entropy')


In [52]:
clf.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [54]:
y_pred =  clf.predict(X_test)
y_pred

array([0], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
print('Accuracy Score on train data: ', accuracy_score(y_true=y_train, y_pred=clf.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=y_test, y_pred=y_pred))


Accuracy Score on train data:  1.0
Accuracy Score on test data:  1.0


In [56]:
clf.predict(test_new_X)

array([0, 0, 0, 0, 0], dtype=int64)

Solution