Problem Statement
Sentiment analysis remains one of the key problems that has seen extensive application of natural language processing. This time around, given the tweets from customers about various tech firms who manufacture and sell mobiles, computers, laptops, etc, the task is to identify if the tweets have a negative sentiment towards such companies or products.

 

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np
import nltk
from sklearn.datasets import load_files
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pickle
import re

In [2]:
path_test=r"E:\APEXTECHNOMATICS\sentimental analysis\test.csv"
path_train=r"E:\APEXTECHNOMATICS\sentimental analysis\train.csv"
path_sample=r"E:\APEXTECHNOMATICS\sentimental analysis\sample.csv"

In [3]:
test_data=pd.read_csv(path_test,index_col=0)
train_data=pd.read_csv(path_train,index_col=0)
sample_data=pd.read_csv(path_sample,index_col=0)
test_data.head()


tweet
id                                                     
7921  I hate the new #iphone upgrade. Won't let me d...
7922  currently shitting my fucking pants. #apple #i...
7923  I'd like to puts some CD-ROMS on my iPad, is t...
7924  My ipod is officially dead. I lost all my pict...
7925  Been fighting iTunes all night! I only want th...

In [4]:
train_data.head()


label                                              tweet
id                                                          
1       0  #fingerprint #Pregnancy Test https://goo.gl/h1...
2       0  Finally a transparant silicon case ^^ Thanks t...
3       0  We love this! Would you go? #talk #makememorie...
4       0  I'm wired I know I'm George I was made that wa...
5       1  What amazing service! Apple won't even talk to...

In [5]:
sample_data.head()

label
id         
7921      0
7922      0
7923      0
7924      0
7925      0

In [6]:
print(sample_data.describe())
print(train_data.describe())
print(test_data.describe())

        label
count  1953.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
             label
count  7920.000000
mean      0.255808
std       0.436342
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000
                                                    tweet
count                                                1953
unique                                               1953
top     Missing this! #jaccuzi #rooftop #costacanaria ...
freq                                                    1


In [10]:
target_X=train_data["label"]
train_X=train_data["tweet"]

In [11]:
X,y=train_X,target_X

In [12]:
with open("X.pickle","wb") as f:
    pickle.dump(X,f)

with open("y.pickle","wb") as f:
    pickle.dump(y,f)

In [13]:
with open("X.pickle","rb") as f:
    Xp=pickle.load(f)
    
with open("y.pickle","rb") as f:
    yp=pickle.load(f)
    #JUST IN CASE, IF LOADING TAKES TOO MUCH TIME

In [14]:
corpus=[]
#for i in range(0,len(X["tweet"])):
#X,y=train_X,target_X
for tweet in train_X:
    #print(i)
    tweet=re.sub(r"\W"," ",tweet)#removing ! like
    tweet=tweet.lower()
    tweet=re.sub(r"\s+[a-z]\s+"," ",tweet)#removing single character a i etc also going to use stopwords later
    tweet=re.sub(r"^[a-z]\s+"," ",tweet)#single char in starting 
    tweet=re.sub(r"\s+"," ",tweet)#extra spaces removing
    corpus.append(tweet)

In [19]:
y_tweet=test_data["tweet"]
#for i in y_tweet:
    #print(i)
#y_tweet

In [20]:
#y_tweet=y["tweet"]

corpus_test=[]
for tweet in y_tweet:
    #print(tweet)
    tweet=re.sub(r"\W"," ",tweet)#removing ! like
    tweet=tweet.lower()
    tweet=re.sub(r"\s+[a-z]\s+"," ",tweet)#removing single character a i etc also going to use stopwords later
    tweet=re.sub(r"^[a-z]\s+"," ",tweet)#single char in starting 
    tweet=re.sub(r"\s+"," ",tweet)#extra spaces removing
    corpus_test.append(tweet)

In [49]:
#corpus
#corpus_test

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(max_features=1435,min_df=3,max_df=0.6,stop_words=stopwords.words("english"))

In [24]:
X_arr=vectorizer.fit_transform(corpus).toarray()

In [25]:
from sklearn.feature_extraction.text import TfidfTransformer
transform=TfidfTransformer()
X_arr=transform.fit_transform(X_arr).toarray()

In [31]:
#train and target
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_arr,target_X,test_size=0.2,random_state=0)#random state is 0 so we get the same results
#text_train,text_test,sent_train,sent_test

In [32]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6336, 1435)
(6336,)
(1584, 1435)
(1584,)


In [33]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()


In [34]:
#target_X

In [35]:
#target_X,text_X
classifier.fit(X_train,y_train)#model 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
#test file to final test
y_arr=vectorizer.fit_transform(corpus_test).toarray()
y_arr=transform.fit_transform(y_arr).toarray()

In [37]:
predict=classifier.predict(X_test)

In [38]:
predict

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,predict)

In [42]:
cm

array([[1088,   90],
       [ 108,  298]], dtype=int64)

In [40]:
cm[0][0]+cm[1][1]

1386

In [46]:
(1386/(1088+90+108+298))*100

87.5

In [47]:
#pickle storing model
with open ("classifier","wb") as f:
    pickle .dump(classifier,f)

In [50]:
y_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
pridict_test=classifier.predict(y_arr)

In [52]:
pridict_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
df = pd.DataFrame(pridict_test) 
  
# saving the dataframe 
df.to_csv('file1.csv') 